require 'spec_helper'

describe "A simple map rendering" do
  it "outputs the expected empty map" do
    map = Map.new(10, 10)
    expected_string = <<-EOS
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
EOS
    Renderer::Map.new(map).to_s.should == expected_string.chop
  end

  it "outputs the expected map with a power plant" do
    map = Map.new(10, 10)
    map.cell_at(Map::Point.new(0, 0)) << PowerPlant.new(map)
    expected_string = <<-EOS
P.........
..........
..........
..........
..........
..........
..........
..........
..........
..........
EOS
    Renderer::Map.new(map).to_s.should == expected_string.chop
  end

  it "outputs the expected map with a power plant after a tick" do
    map = Map.new(10, 10)
    map.cell_at(Map::Point.new(0, 1)) << PowerPlant.new(map)
    map.tick
    expected_string = <<-EOS
z.........
P.........
..........
..........
..........
..........
..........
..........
..........
..........
EOS
    Renderer::Map.new(map).to_s.should == expected_string.chop
  end
  it "outputs the expected map with a power plant after two ticks" do
    map = Map.new(10, 10)
    map.cell_at(Map::Point.new(0, 2)) << PowerPlant.new(map)
    map.tick
    map.tick
    expected_string = <<-EOS
z.........
z.........
P.........
..........
..........
..........
..........
..........
..........
..........
EOS
    Renderer::Map.new(map).to_s.should == expected_string.chop
  end

  it "outputs the expected map with a road" do
    map = Map.new(10, 10)
    map.cell_at(Map::Point.new(0, 2)) << PowerPlant.new(map)
    map.cell_at(Map::Point.new(0,1)) << Structure::Road.new(map)
    expected_string = <<-EOS
..........
=.........
P.........
..........
..........
..........
..........
..........
..........
..........
EOS
    Renderer::Map.new(map).to_s.should == expected_string.chop
  end
end
