require 'spec_helper'

describe "A simple map rendering" do
  it "outputs the expected empty map" do
    map = Map.new(10, 10)
    expected_string = <<-EOS
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
EOS
    Renderer::Map.new(map).to_s.should == expected_string.chop
  end

  it "outputs the expected map with a power plant" do
    map = Map.new(10, 10)
    map.cell_at(Map::Point.new(0, 0)) << PowerPlant.new(map)
    expected_string = <<-EOS
P.........
..........
..........
..........
..........
..........
..........
..........
..........
..........
EOS
    Renderer::Map.new(map).to_s.should == expected_string.chop
  end
end
